package com.aaratech.leasing.projections;

public interface BucketWise {

	//select COALESCE(COMPANY_CODE,'') as COMPANY_CODE,
	public String getCOMPANY_CODE();
	//COALESCE(SUM(TOTAL_AMOUNT_DUE), 0) as TOTAL_AMOUNT_DUE,
	public Integer getTOTAL_AMOUNT_DUE();
	//count(TOTAL_AMOUNT_DUE) as COUNT_TOTAL_AMOUNT_DUE,
	public Integer getCOUNT_TOTAL_AMOUNT_DUE();
	//COALESCE(SUM(CURRENT_BALANCE),0) as CURRENT_BALANCE,
	public Integer getCURRENT_BALANCE();
	//count(CURRENT_BALANCE) as TOTAL_CURRENT_BALANCE,
	public Integer getTOTAL_CURRENT_BALANCE();
	//COALESCE(SUM(X_DAYS_AMOUNT),0) as X_DAYS_AMOUNT,
	public Integer getX_DAYS_AMOUNT();
	//count(X_DAYS_AMOUNT) as TOTAL_X_DAYS_AMOUNT, 
	public Integer getTOTAL_X_DAYS_AMOUNT();
	//COALESCE(SUM(DAYS_30_AMOUNT), 0) as DAYS_30_AMOUNT, 
	public Integer getDAYS_30_AMOUNT();
	//COALESCE(count(DAYS_30_AMOUNT) , 0) as TOTAL_COUNT_DAYS_30_AMOUNT,
	public Integer getTOTAL_COUNT_DAYS_30_AMOUNT();
	//COALESCE(SUM(DAYS_60_AMOUNT), 0) as DAYS_60_AMOUNT,
	public Integer getDAYS_60_AMOUNT();
	//COALESCE(count(DAYS_60_AMOUNT), 0) as TOTAL_COUNT_DAYS_60_AMOUNT,
	public Integer getTOTAL_COUNT_DAYS_60_AMOUNT();
	//COALESCE(SUM(DAYS_90_AMOUNT),0) as DAYS_90_AMOUNT,
	public Integer getDAYS_90_AMOUNT();
	//COALESCE(count(DAYS_90_AMOUNT), 0) as TOTAL_COUNT_DAYS_90_AMOUNT,
	public Integer getTOTAL_COUNT_DAYS_90_AMOUNT();
	//COALESCE(SUM(DAYS_120_AMOUNT),0) as DAYS_120_AMOUNT,
	public Integer getDAYS_120_AMOUNT();
	//COALESCE(count(DAYS_120_AMOUNT),0) as TOTAL_DAYS_120_AMOUNT,
	public Integer getTOTAL_DAYS_120_AMOUNT();
	//COALESCE(SUM(DAYS_150_AMOUNT),0) as DAYS_150_AMOUNT, 
	public Integer getDAYS_150_AMOUNT();
	//COALESCE(count(DAYS_150_AMOUNT),0) as TOTAL_DAYS_150_AMOUNT,
	public Integer getTOTAL_DAYS_150_AMOUNT();
	//COALESCE(SUM(DAYS_180_AMOUNT),0) as DAYS_180_AMOUNT,
	public Integer getDAYS_180_AMOUNT();
	//COALESCE(COUNT(DAYS_180_AMOUNT),0) as TOTAL_DAYS_180_AMOUNT,
	public Integer getTOTAL_DAYS_180_AMOUNT();
	//COALESCE(SUM(DAYS_210_AMOUNT),0) as DAYS_210_AMOUNT,
	public Integer getDAYS_210_AMOUNT();
	//COALESCE(COUNT(DAYS_210_AMOUNT),0) as TOTAL_DAYS_210_AMOUNT,
	public Integer getTOTAL_DAYS_210_AMOUNT();
	//COALESCE(SUM(DAYS_240_AMOUNT),0) as DAYS_240_AMOUNT,
	public Integer getDAYS_240_AMOUNT();
	//COALESCE(COUNT(DAYS_240_AMOUNT),0) as TOTAL_DAYS_240_AMOUNT,
	public Integer getTOTAL_DAYS_240_AMOUNT();
	//COALESCE(SUM(DAYS_270_AMOUNT),0) as DAYS_270_AMOUNT,
	public Integer getDAYS_270_AMOUNT();
	//COALESCE(COUNT(DAYS_270_AMOUNT),0) as TOTAL_DAYS_270_AMOUNT,
	public Integer getTOTAL_DAYS_270_AMOUNT();
	//COALESCE(SUM(DAYS_300_AMOUNT),0) as DAYS_300_AMOUNT,
	public Integer getDAYS_300_AMOUNT();
	//COALESCE(COUNT(DAYS_300_AMOUNT),0) as TOTAL_DAYS_300_AMOUNT,
	public Integer getTOTAL_DAYS_300_AMOUNT();
	//COALESCE(SUM(DAYS_330_AMOUNT),0) as DAYS_330_AMOUNT,
	public Integer getDAYS_330_AMOUNT();
	//COALESCE(COUNT(DAYS_330_AMOUNT),0) as TOTAL_DAYS_330_AMOUNT,
	public Integer getTOTAL_DAYS_330_AMOUNT();
	//COALESCE(SUM(DAYS_360_AMOUNT),0) as DAYS_360_AMOUNT, 
	public Integer getDAYS_360_AMOUNT();
	//COALESCE(COUNT(DAYS_360_AMOUNT),0) as TOTAL_DAYS_360_AMOUNT
	public Integer getTOTAL_DAYS_360_AMOUNT();
}
